### ISSUE TITLE
Is it RESTful to have chirps and chirp routes?

### ISSUE THREAD

**Issue by hseeberger** [britter/reactive-chirps#1]
I'm not an expert in that field, but AFAIK a RESTful API should use a single endpoint for all matters regarding a resource. In particular I think you should use
- `GET /chirps` to get all chirps
- `GET /chirps/<id>` to get the chirp with the given id

**Comment by britter** [comment]
You're right. I wanted it to do the way the [GitHub API](https://developer.github.com/v3/) is modeled, but got confused with the way the GitHub web UI build URLs:

Web UI: 
 - https://github.com/britter/reactive-chirps/commits - List of all commits
 - https://github.com/britter/reactive-chirps/commit/:sha - single commit

API:
 - https://api.github.com/repos/britter/reactive-chirps/commits - List of all commits
 - https://api.github.com/repos/britter/reactive-chirps/commits/:sha - single commit

I pushed #2 as proposal to fix this.
